project_id         = "******"
region             = "europe-central2"
zones              = ["europe-central2-a", "europe-central2-b", "europe-central2-c"]
name               = "gke-cluster"
machine_type       = "g1-small"
min_count          = 1
max_count          = 2
disk_size_gb       = 10
service_account    = "**********"
initial_node_count = 1
network = "default"
subnetwork = "default"
disktype = "pd-standard"
nodepoolname = "Nodepool1"
